### ISSUE TITLE
Make Archlinux package please

### ISSUE THREAD

**Issue by imShara** [brandizzi/input-device-indicator#6]
Or official AUR script. Thanks!

**Comment by brandizzi** [comment]
Hello! I acknowledge the request. I just need some time to research, but I'll look at it!

**Comment by Avinash-Bhat** [comment]
@imShara created at https://aur.archlinux.org/packages/input-device-indicator/

**Comment by imShara** [comment]
@Avinash-Bhat blilliant, thanks!

**Comment by brandizzi** [comment]
Wow, amazing! Thank you so much, @Avinash-Bhat!

**Comment by brandizzi** [comment]
BTW @Avinash-Bhat, did you have to create some files to do that? If so, we may merge them into the repository, if you're willing to submit a pull request. Open to you, of course :) i'm already deeply thankful for your help.

**Comment by Avinash-Bhat** [comment]
It's maintained in the aur git repo itself.
